### ISSUE TITLE
Team member emails not received

### ISSUE THREAD

**Issue by obibring** [apex/logs-js#3]
Hey there, tried sending invites to my team members but neither of them received the invitation email. My email is orr@plater.com. Thanks!

**Comment by tj** [comment]
Ahh sorry about that, they should still be able to sign-in, it just adds a database record at the moment.

For security reasons I can't send an email with a sign-in token unfortunately, but I should at least send a link to the UI so they can sign-in from there instead of having to share the link with co-workers.

**Comment by obibring** [comment]
Got it, thanks for the quick reply!

**Comment by obibring** [comment]
They were able to sign in but seeing `403` responses trying to load the UI

**Comment by obibring** [comment]
Sorry -- user error on the last comment.

**Comment by tj** [comment]
no problem! I'll get that fixed in the next release, let me know if there are any other issues

**Comment by obibring** [comment]
🙏
